theme: jekyll-theme-minimal
logo: https://www.google.com/search?q=frog&sca_esv=589207572&rlz=1C1ONGR_enUS1004US1004&tbm=isch&source=iu&ictx=1&vet=1&fir=QFkXcKGqvQpKiM%252CQi3X-bx2NkUe5M%252C_%253B3G6Uuqaq7mMBHM%252CuA8NQHxJQ5iLnM%252C_%253BEOaNcClapgwTwM%252Ca4LF6s21-babaM%252C_%253B8BY_DHD1E2OtjM%252CAQB6hAc2YdocaM%252C_&usg=AI4_-kSbbcU7hQh6q_2bVICbyB7QtGAB_Q&sa=X&ved=2ahUKEwjNytOs7oCDAxV9KEQIHUEhDS0Q_h16BAhgEAE#imgrc=3G6Uuqaq7mMBHM
title: Introduction to Bioinformatics
