---
title: "lab9"
author: "Kelly Isbell (A59019188)"
format: pdf
---
```{r}
fna.data <- "WisconsinCancer.csv"
wisc.df <- read.csv(fna.data, row.names=1)
View(wisc.df)
```

```{r}
wisc.data <- wisc.df[,-1]
diagnosis <- wisc.df[,1]
```

```{r}
nrow(wisc.data)
#Q1 there are 569 observations in this dataset
```
```{r}
table(diagnosis)
#Q2 There are 212 observations with a malignant diagnosis in this dataset.
```
```{r}
length(grep("_mean", colnames(wisc.df), value=TRUE))
#Q3 There are 10 variables that are suffixed with _mean.
```
```{r}
colMeans(wisc.data)
apply(wisc.data, 2, sd)
```
```{r}
wisc.pr <- prcomp(wisc.data, scale=TRUE)
summary(wisc.pr)
```
```{r}
summary(wisc.pr)
```
```{r}
#Q4 44.27% of the original variance is captured by PC1

#Q5 3 PCs are required to describe at least 70% of the original variance.

#Q6 7 PCs are required to describe at least 90% of the original variance.
```

```{r}
biplot(wisc.pr)
#Q7 This plot is extremely difficult to understand because there is a lot of overlap of components
```
```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,2], col=as.factor(diagnosis), xlab = "PC1", ylab= "PC2")
```
```{r}
plot(wisc.pr$x[,1], wisc.pr$x[,3], col=as.factor(diagnosis), xlab = "PC1", ylab= "PC3")
#Q8 The seperation between the red and black points is more defined in the first plot (PC1 vs. PC2) in comparison to the 2nd plot (PC1 vs PC3)
```
```{r}
df <- as.data.frame(wisc.pr$x)
df$diagnosis <- diagnosis
library(ggplot2)
ggplot(df) + 
  aes(PC1, PC2, col=diagnosis) + 
  geom_point()
```
```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```
```{r}
pve <- pr.var/sum(pr.var)
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```
```{r}
barplot(pve, ylab = "Precent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
```
```{r}
#install.packages("factoextra")
library(factoextra)
fviz_eig(wisc.pr, addlabels = TRUE)
```


```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method = "complete") 
plot(wisc.hclust)
abline(wisc.hclust, col="red", lty=2)
#Q10 the height at which the clustering model has 4 clusters is 19
```

```{r}
wisc.hclust.clusters <-cutree(wisc.hclust, h=19)
table(wisc.hclust.clusters, diagnosis)
```
```{r}
wisc.hclust.complete <- hclust(data.dist, method = "complete") 
plot(wisc.hclust.complete)

wisc.hclust.single <- hclust(data.dist, method = "single")
plot(wisc.hclust.single)

wisc.hclust.average <- hclust(data.dist, method = "average") 
plot(wisc.hclust.average)

wisc.hclust.ward.D2 <- hclust(data.dist, method = "ward.D2") 
plot(wisc.hclust.ward.D2)

#Q12 ward.D2 is the best method because it create groups that has minimized variance within clusters
```
```{r}
wisc.pr.hclust <- hclust(data.dist, method = "ward.D2") 
plot(wisc.pr.hclust)
grps <- cutree(wisc.pr.hclust, k=2)
table(grps)
```
```{r}
table(grps, diagnosis)
```
```{r}
plot(wisc.pr$x[,1:2], col=grps)
```
```{r}
#plot(wisc.pr$x[,1:2], col=diagnosis)
```

```{r}
g <- as.factor(grps)
levels(g)
```
```{r}
g <- relevel(g,2)
levels(g)
```

```{r}
plot(wisc.pr$x[,1:2], col=g)
```
```{r}
#install.packages("rgl")
library(rgl)
#plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=grps)
```

```{r}
wisc.pr.hclust2 <- hclust(data.dist, method = "ward.D2")
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust2, k=2)
table(wisc.pr.hclust.clusters, diagnosis)

#Q13 There are some false positives and false negatives, so the clustering is not perfect
```
```{r}
table(wisc.hclust.clusters, diagnosis)
#Q14 The clustering is comparable
```
```{r}
#Q15 optional
```

```{r}
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
npc
```
```{r}
plot(wisc.pr$x[,1:2], col=g)
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
text(npc[,1], npc[,2], c(1,2), col="white")
#Q16 Patient 1 because cluster 1 (black) is more likely to represent a malignant observation
```

