---
title: "Class 5: Data Visualization with ggplot"
author: "Kelly (A59019188)"
format: pdf
---

## Using ggplot
Must download any package functions with "library()" call  prior to using that package in a script
```{r}
library(ggplot2)
# install.packages("farver")
ggplot(cars)
```
```{r}
plot(cars)
```
To use ggplot, you need
1. Data (data.frame)
2. aesthetics (aes() values - how the data maps to the plot)
3. geoms (how I want things drawn)
```{r}
ggplot(cars) + 
  aes(x=speed, y=dist) + 
  geom_point() + 
  labs(title="Speed and Stopping Distance of Cars", x="Speed (MPH)", y="Stopping Distance (ft)", subtitle="xyz", caption="Dataset: 'cars'") +
  geom_smooth(method="lm", se=FALSE) +
  theme_bw()
```
```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
nrow(genes)
colnames(genes)
table(genes$State)
round(table(genes$State)/nrow(genes) * 100, 2)
p <- ggplot(genes) +
  aes(x = Condition1, y = Condition2, col=State) + geom_point()
p + scale_colour_manual( values=c("blue","gray","red") )

```
```{r}
# install.packages("gapminder")
library(gapminder)
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"
gapminder <- read.delim(url)
# install.packages("dplyr")
library(dplyr)
gapminder_2007 <- gapminder %>% filter(year==2007)
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, size=pop) +
  geom_point(alpha=0.5) +
  scale_size_area(max_size = 10)
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)
ggplot(gapminder_1957) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) + 
  geom_point(alpha=0.7) +
  scale_size_area(max_size=15) +
  facet_wrap(~year)
```

